name: "Cover Agent CI pipeline"
description: "test"
author: "Kousik Mitra"
inputs:
  sourceDir:
    description: "Source code dir"
    required: true
  desiredCoverage:
    description: "Desired coverage"
    default: "70"
  maxIterations:
    description: "Max iterations to run to acheive desired coverage"
    default: "1"
  modelName:
    description: "Name of the model"
    required: true
  apiEndpoint:
    description: "API Endpoint to access the model"
    required: true
  githubToken:
    description: "github token"
    required: true
outputs:
  previousCoverage:
    description: "Previous coverage"
    value: ${{ steps.cover-agent-ci-action.outputs.previousCoverage }}
  currentCoverage:
    description: "Current coverage"
    value: ${{ steps.cover-agent-ci-action.outputs.currentCoverage }}
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install cover-agent
      shell: sh
      run: |
        pip install git+https://github.com/Codium-ai/cover-agent.git

    - name: setup go
      uses: actions/setup-go@v2
      with:
        go-version: "^1.20.0"

    - name: Install go coverage tools
      shell: sh
      run: |
        go version
        go install github.com/axw/gocov/gocov@v1.1.0
        go install github.com/AlekSi/gocov-xml@v1.1.0

    - name: installing dep
      shell: sh
      run: go mod tidy

    - name: Running tests Before Test Gen AI
      shell: sh
      run: go test -v -coverprofile=coverageBefore.out ./...

    - name: Extract coverage summary Before Test Gen AI
      shell: sh
      run: |
        go tool cover -func=coverageBefore.out | grep total | awk '{print $3}' > coverageBefore.txt

    # - name: Run cover-agent-ci
    #   id: cover-agent-ci-action
    #   uses: kousikmitra/cover-agent-ci/cover-agent-action@main
    #   with:
    #     sourceDir: ${{ inputs.sourceDir }}
    #     desiredCoverage: ${{ inputs.desiredCoverage }}
    #     maxIterations: ${{ inputs.maxIterations }}
    #     modelName: ${{ inputs.modelName }}
    #     apiEndpoint: ${{ inputs.apiEndpoint }}
    #     githubToken: ${{ inputs.githubToken }}

    - name: Running tests After Test Gen AI
      shell: sh
      run: go test -v -coverprofile=coverageAfter.out ./...

    - name: Extract coverage summary After Test Gen AI
      shell: sh
      run: |
        go tool cover -func=coverageAfter.out | grep total | awk '{print $3}' > coverageAfter.txt

    - name: Comment coverage summary on PR
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.githubToken }}
        script: |
          const fs = require('fs');
          const coverageBefore = fs.readFileSync('coverageBefore.txt', 'utf8').trim();
          const coverageAfter = fs.readFileSync('coverageAfter.txt', 'utf8').trim();
          const comment = `### Code Coverage Summary\n\nTotal Coverage Before Test Gen AI: ${coverageBefore}\n\n\nVoila!! Total Coverage After Test Gen AI: ${coverageAfter}`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });

    - name: "Remove files"
      shell: sh
      run: |
        ls
        # rm run.log test_results.html coverageBefore.* coverageAfter.*
        git diff

    - name: Create PR with changes
      id: create-pr
      uses: peter-evans/create-pull-request@v6
      with:
        branch: "testgen/${{ github.head_ref || github.ref_name }}"
        base: ${{ github.head_ref || github.ref_name }}
        commit-message: Add generated tests
        title: "Generated test for PR #${{ github.event.number }}"
        token: ${{ inputs.githubToken }}
