name: "Cover Agent CI pipeline"
description: "test"
author: "Kousik Mitra"
inputs:
  sourceDir:
    description: "Source code dir"
    required: true
  desiredCoverage:
    description: "Desired coverage"
    default: "70"
  githubToken:
    required: true
    description: "github token"
outputs:
  previousCoverage:
    description: "Previous coverage"
  currentCoverage:
    description: "Current coverage"
runs:
  using: "node20"
  main: "index.js"
