name: "Cover Agent CI pipeline"
description: "test"
author: "Kousik Mitra"
inputs:
  sourceDir:
    description: "Source code dir"
    required: true
  desiredCoverage:
    description: "Desired coverage"
    default: "70"
outputs:
  previousCoverage:
    description: "Previous coverage"
  currentCoverage:
    description: "Current coverage"
runs:
  using: "docker"
  image: "Dockerfile"
