name: "Cover Agent CI pipeline"
description: "test"
author: "Kousik Mitra"
inputs:
  sourceDir:
    description: "Source code dir"
    required: true
  desiredCoverage:
    description: "Desired coverage"
    default: "70"
  maxIterations:
    description: "Max iterations to run to acheive desired coverage"
    default: "1"
  modelName:
    description: "Name of the model"
    required: true
  apiEndpoint:
    description: "API Endpoint to access the model"
    required: true
  githubToken:
    description: "github token"
    required: true
outputs:
  previousCoverage:
    description: "Previous coverage"
    value: ${{ steps.cover-agent-ci-action.outputs.previousCoverage }}
  currentCoverage:
    description: "Current coverage"
    value: ${{ steps.cover-agent-ci-action.outputs.currentCoverage }}
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install cover-agent
      shell: sh
      run: |
        pip install git+https://github.com/Codium-ai/cover-agent.git

    - uses: actions/setup-go@v5
      with:
        go-version: ">=1.20.0"

    - name: Install go coverage tools
      shell: sh
      run: |
        go version
        go install github.com/axw/gocov/gocov@v1.1.0
        go install github.com/AlekSi/gocov-xml@v1.1.0

    - name: Run cover-agent-ci
      id: cover-agent-ci-action
      uses: kousikmitra/cover-agent-ci/cover-agent-action@main
      with:
        sourceDir: ${{ inputs.sourceDir }}
        desiredCoverage: ${{ inputs.desiredCoverage }}
        maxIterations: ${{ inputs.maxIterations }}
        modelName: ${{ inputs.modelName }}
        apiEndpoint: ${{ inputs.apiEndpoint }}
        githubToken: ${{ inputs.githubToken }}
    - shell: sh
      run: |
        git diff

    - name: Create PR with changes
      shell: sh
      run: |
        git config --global user.email "kousikmitra12@gmail.com"
        git config --global user.name "Kousik Mitra"
        targetBranch=$(git rev-parse --abbrev-ref HEAD)
        testgenBranch=testgen/$targetBranch
        git checkout -b "testgen/$testgenBranch"
        # Only add go files for now
        git add **/*.go && git commit -m "Add generated tests"
        gh pr create --base "$targetBranch" --head "$testgenBranch" --title "Generated test for $targetBranch" --fill-verbose
      env:
        GH_TOKEN: ${{ inputs.githubToken }}

  # using: "node20"
  # main: "index.js"
