name: Integration Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        # Put your action repo here
        uses: kousikmitra/cover-agent-ci@main
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.changes }}"
